-- AlterTable
ALTER TABLE "Solve" ADD COLUMN     "executionTime" INTEGER DEFAULT 0,
ADD COLUMN     "submittedAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "testsPassed" INTEGER DEFAULT 0,
ADD COLUMN     "totalTests" INTEGER DEFAULT 0;
